services:
  backend:
    build:
      context: ./backend
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.20.111/entraide_logistique_db
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=

  frontend:
    build:
      context: ./frontend
    ports:
      - "0.0.0.0:5173:80"
    depends_on:
      - backend
